### ISSUE TITLE
WARNING: Tried to load angular more than once

### ISSUE THREAD

**Issue by yoyoprs** [subarroca/ng-password-strength#12]
This error happens when I refresh the page (and ng-password-strenght is loaded in template)
AngularJS v1.3.15

**Comment by subarroca** [comment]
I'll have a look at it

**Comment by yoyoprs** [comment]
You have new about this bug?

**Comment by subarroca** [comment]
I've tried it and I could not reproduce it. Could you set up a plunkr?

**Comment by yoyoprs** [comment]
This console log is in vendor.js script. 
Could you provide the source of vendors.js, i will try to determine why this message appears.
My app is very complex with a lot of dependencies, i guess it comes from there; too complicated to reproduce on a plunkr.

**Comment by subarroca** [comment]
All scripts in vendor.js can be obtained through bower. You could fork the project and do bower install. This way you can see all dependencies and do some debugging.
