### ISSUE TITLE
Ng password strength along with min length

### ISSUE THREAD

**Issue by amirshakya2010** [subarroca/ng-password-strength#15]
My issue is like this, when i put the min length validation = 7 along with password strength, the password strength start to work after 7 characters is entered. 

What is the solution for this ?

**Comment by intellix** [comment]
Could be caused by "alert" `outterClass` rather than danger, so you only see a password when it's in warning state. I've fixed this in #16

**Comment by subarroca** [comment]
I'll be releasing a new version today, I hope, with some changes. Could you try it and get back to me if it still has problems?
