### ISSUE TITLE
Change the in-line template to templateUrl

### ISSUE THREAD

**Issue by davidnovodchuk** [subarroca/ng-password-strength#17]
I want to use the ng-password-strength directive. However, I want to customize the template. I cannot do that because this is an in-line template. If it was a separate html file, I could overwrite it.

**Comment by mbuttu** [comment]
It would be nice to be able to customize the HTML templates included in this directive.

Any updates on merging this in @subarroca?

**Comment by davidnovodchuk** [comment]
I think that the subarroca repository is not maintained any more. My PR was never commented or merged and that last commit to the repository happened on Aug 5. If I will get any notification about my PR, I will let you know.
