### ISSUE TITLE
Check for dictionary words?

### ISSUE THREAD

**Issue by andreis** [subarroca/ng-password-strength#2]
I like your idea of quantising aspects of the password as plusses and minuses, however I think dictionary words (e.g. milk, flowers, yellow) should be among the negative criteria.

:+1:

**Comment by worldspawn** [comment]
I looked at another password strength module that had dictionaries. It added a considerably amount heft to the payload, some 300KB+ when gzipped.

**Comment by andreis** [comment]
A 300KB download in the name of security isn't that bad. You'd have to make API calls with the plaintext passwords, even if you'd use HTTPS it'd still be a bad idea. What you can do is hash the passwords and check the hashes of known bad passwords server-side, that's what we do at Lavaboom.
