### ISSUE TITLE
Export the service

### ISSUE THREAD

**Issue by oliversalzburg** [subarroca/ng-password-strength#20]
I was wondering why the service wasn't exposed in the published module? I use this project with angular-material and the directive doesn't really work in that environment. 

Rolling my own strength indicator from the `app` directory worked like a charm though. Maybe it would make sense to expose that service for users.

**Comment by subarroca** [comment]
@intellix has made a pull request with what this. I'll be releasing a new version today I hope. Let me know if you have any problem.
