### ISSUE TITLE
angular 1.4?

### ISSUE THREAD

**Issue by bdkent** [subarroca/ng-password-strength#21]
Is there any reason this won't work with angular 1.4.x?

The `bower.json` has `"angular": "~1.3.15"`.

**Comment by subarroca** [comment]
It should work, it's fixed in 1.3.15 because at that moment 1.4 was probably not yet released and wouldn't risk it

**Comment by wcjr** [comment]
I'd benefit greatly from your code but will have to fork and upgrade angular if you're afraid to do it...let us know what your plans are, thanks.

**Comment by subarroca** [comment]
I'll be releasing a new version today I hope. It will be based on 1.4. Let me know if you have any problem.

**Comment by wcjr** [comment]
Will do, thanks for upgrading.  Happy New Year!
