### ISSUE TITLE
Little mistake

### ISSUE THREAD

**Issue by dom-will** [subarroca/ng-password-strength#27]
you have a little mistake:

              getClass = function(s) {
                switch (Math.round(s / 33)) {
                  case 0:
                  case 1:
                    return {
                     --> inner: scope.outterClassPrefix + 'danger', <--
                     --> outter: scope.innerClassPrefix + 'alert' <--
                    };
                  case 2:
                    return {
                      outter: scope.outterClassPrefix + 'warning',
                      inner: scope.innerClassPrefix + 'warning'
                    };
                  case 3:
                    return {
                      outter: scope.outterClassPrefix + 'success',
                      inner: scope.innerClassPrefix + 'success'
                    };
                }
              };

Tanks for great tool! ;)

**Comment by subarroca** [comment]
Thanks for noticing!
I'll be releasing a new version today I hope and it has this fixed.
You're welcome for your supportive message!
