### ISSUE TITLE
Why is this plugin coupled with bootstrap?

### ISSUE THREAD

**Issue by dkarter** [subarroca/ng-password-strength#4]
I think it would be best to avoid coupling it with a specific UI framework (bootstrap sass in this instance). This will allow people using other frameworks such as foundation/bourbon-neat-refills to use it as well.

If you decide to keep the coupling to bootstrap maybe you should change the name of the plugin.

Thanks!

**Comment by subarroca** [comment]
Hi!
It's coupled with bootstrap because it's what I have been using. In fact to decouple this I should write a whole new css for something that it has already been done.

I'll bear in mind the plugin name for new projects, but I'll keep this name to avoid problems with people already using it.

**Comment by subarroca** [comment]
I just decoupled that. Now there are no stylesheets dependencies and you can just assign classes to inner and outer elements. You can even assign 'bootstrap' or 'foundation' to the mode.
Hope this helps

**Comment by dkarter** [comment]
Thanks!
