### ISSUE TITLE
Conflict with core Lodash dependency (AMD)

### ISSUE THREAD

**Issue by shoaibmerchant** [subarroca/ng-password-strength#9]
Hi I am using ng-password-strength in my application which has a direct dependency to ng-lodash but my application is already loading the core lodash module which is a dependency to another plugin. Ng-lodash implements its own wrapper over lodash but returns the same module name 'lodash' which creates a conflict in RequireJS.

```
Error: Mismatched anonymous define() module: function (){return Xb}
http://requirejs.org/docs/errors.html#mismatch {requireType: "mismatch", requireModules: undefined, stack: (...), message: "Mismatched anonymous define() module: function (){…b}↵http://requirejs.org/docs/errors.html#mismatch"}
```

The above is because there are two anonymous modules now with the name 'lodash'.

A lot of Angular modules use the core lodash instead of the wrapper to make sure they are up to date with the latest version of lodash. There are no changes required to switch to the core lodash plugin. I can do this on a fork but I wanted to know if this can be merged on the master. I can submit a PR.

P.S - I spent a lot of time trying to find what was going wrong. A lot of people will face the same issue if they are using lodash also.

**Comment by subarroca** [comment]
Hi, thanks for the tip. 
I'm working in a new release that will come out in a few days. If you need it really fast make a PA, otherwise I'll remove the dependency this week. 

Thanks

**Comment by subarroca** [comment]
Hi!

I just removed the dependency. You can check v0.2.0.
If there's any other issue please let me know.

Thanks

**Comment by shoaibmerchant** [comment]
Thank you for the super fast turnaround :)
